(function(root){
'use strict';
const enc=new TextEncoder(),xml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function crc32(a){let c=0xffffffff;for(const x of a){c^=x;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function zip(files){const parts=[],directory=[];let offset=0;const header=(n)=>{const a=new Uint8Array(n);return [a,new DataView(a.buffer)];};
 for(const [name,data]of Object.entries(files)){const b=typeof data==='string'?enc.encode(data):data,n=enc.encode(name),crc=crc32(b);const [h,v]=header(30);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,b.length,true);v.setUint32(22,b.length,true);v.setUint16(26,n.length,true);parts.push(h,n,b);const [d,w]=header(46);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint32(16,crc,true);w.setUint32(20,b.length,true);w.setUint32(24,b.length,true);w.setUint16(28,n.length,true);w.setUint32(42,offset,true);directory.push(d,n);offset+=30+n.length+b.length;}
 const size=directory.reduce((s,x)=>s+x.length,0),[end,e]=header(22);e.setUint32(0,0x06054b50,true);e.setUint16(8,Object.keys(files).length,true);e.setUint16(10,Object.keys(files).length,true);e.setUint32(12,size,true);e.setUint32(16,offset,true);const all=[...parts,...directory,end],out=new Uint8Array(all.reduce((s,x)=>s+x.length,0));let i=0;for(const a of all){out.set(a,i);i+=a.length;}return out;}
function save(data,name,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function col(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
function xlsx(sheets){const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',files={};files['[Content_Types].xml']=`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((s,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`;
 files['_rels/.rels']='<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>';
 files['xl/workbook.xml']=`<?xml version="1.0"?><workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${xml(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`;
 files['xl/_rels/workbook.xml.rels']=`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((s,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;
 files['xl/styles.xml']=`<?xml version="1.0"?><styleSheet xmlns="${ns}"><numFmts count="1"><numFmt numFmtId="164" formatCode="0.######"/></numFmts><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF123C4A"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFill="1" applyFont="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="2" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
 sheets.forEach((s,i)=>{const width=Math.max(...s.rows.map(r=>r.length));files[`xl/worksheets/sheet${i+1}.xml`]=`<?xml version="1.0"?><worksheet xmlns="${ns}"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${Array.from({length:width},(_,j)=>`<col min="${j+1}" max="${j+1}" width="${s.widths?.[j]||22}" customWidth="1"/>`).join('')}</cols><sheetData>${s.rows.map((r,k)=>`<row r="${k+1}" ht="${k===0?34:s.name==='Notes'?52:30}" customHeight="1">${r.map((v,j)=>typeof v==='number'&&Number.isFinite(v)?`<c r="${col(j)}${k+1}" s="${k===0?1:s.precision?3:2}"><v>${v}</v></c>`:`<c r="${col(j)}${k+1}" t="inlineStr" s="${k===0?1:0}"><is><t xml:space="preserve">${xml(v)}</t></is></c>`).join('')}</row>`).join('')}</sheetData><pageSetup orientation="landscape" paperSize="9"/></worksheet>`;});return zip(files);}
const printable=s=>String(s??'').replace(/[–—−·]/g,'-').replace(/≥/g,'>=').replace(/≤/g,'<=').replace(/×/g,'x').replace(/Ω/g,'ohm').replace(/″/g,"''").replace(/²/g,'^2').replace(/η/g,'eta').replace(/√/g,'sqrt').replace(/[^\x20-\x7E\n]/g,'?');
async function pdf(title,sections,brand){const {PDFDocument,StandardFonts,rgb}=root.PDFLib,doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);doc.setTitle(printable(title));doc.setAuthor(printable(brand.name));let page,y;
 const newPage=()=>{page=doc.addPage([842,595]);y=535;page.drawText(printable(brand.name).slice(0,180),{x:36,y:562,size:Math.min(17,770/bold.widthOfTextAtSize(printable(brand.name).slice(0,180)||'EPS',1)),font:bold,color:rgb(.06,.24,.29)});page.drawText(printable(title).slice(0,115),{x:36,y:543,size:10,font,color:rgb(.3,.38,.4)});};
 const wrap=(txt,width,size=10)=>{const words=printable(txt).split(/\s+/),lines=[];let line='';for(let word of words){while(font.widthOfTextAtSize(word,size)>width){let k=Math.max(1,Math.floor(word.length*width/font.widthOfTextAtSize(word,size)));lines.push(word.slice(0,k));word=word.slice(k);}if(font.widthOfTextAtSize(line+' '+word,size)>width&&line){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);return lines.length?lines:[''];};
 newPage();
 for(const section of sections){if(section.newPage&&y<525)newPage();if(y<90)newPage();y-=18;page.drawText(printable(section.title),{x:36,y,size:13,font:bold,color:rgb(.06,.24,.29)});y-=18;
  for(const paragraph of section.paragraphs||[]){for(const line of wrap(paragraph,770)){if(y<48)newPage();page.drawText(line,{x:36,y,size:10,font});y-=14;}y-=5;}
  if(section.rows){const widths=section.widths||Array(section.rows[0].length).fill(770/section.rows[0].length);const drawRow=(r,head=false)=>{const cells=r.map((v,i)=>wrap(typeof v==='number'?v.toFixed(2):v,widths[i]-10,8)),height=Math.max(...cells.map(a=>a.length))*10+6;if(y-height<38){newPage();if(!head)drawRow(section.rows[0],true);}if(head)page.drawRectangle({x:36,y:y-height,width:770,height,color:rgb(.07,.24,.29)});let x=41;cells.forEach((lines,i)=>{lines.forEach((line,j)=>page.drawText(line,{x,y:y-10-j*10,size:8,font:head?bold:font,color:head?rgb(1,1,1):rgb(.1,.15,.18)}));x+=widths[i];});y-=height;page.drawLine({start:{x:36,y},end:{x:806,y},thickness:.4,color:rgb(.8,.85,.87)});};section.rows.forEach((r,i)=>drawRow(r,i===0));}
 }
 const pages=doc.getPages();pages.forEach((p,i)=>p.drawText(`Energy planning estimate | ${i+1} / ${pages.length}`,{x:36,y:20,size:8,font,color:rgb(.4,.4,.4)}));return doc.save();}
root.EnergyExport={zip,xlsx,pdf,save};if(typeof module==='object')module.exports=root.EnergyExport;
})(globalThis);
