(function(root){'use strict';
const defaults=()=>({loadflow:{voltage:400,minPU:.95,maxPU:1.05,buses:[{name:'Main LV',parent:0,p:80,q:40,r:.008,x:.012,amps:630},{name:'MCC 1',parent:1,p:55,q:30,r:.025,x:.008,amps:250},{name:'Building',parent:1,p:25,q:8,r:.04,x:.01,amps:125}]},fault:{voltage:400,sourceMVA:250,sourceXR:10,kva:1000,z:6,txXR:7,r:.003,x:.002,factor:1},generator:{voltage:400,kva:500,ratedPF:.8,derating:90,loadKW:250,loadPF:.85,units:2,minLoad:30,xd:15},transformer:{kva:1000,hv:11000,lv:400,z:6,core:1.6,copper:12,loadKW:600,pf:.85},pf:{voltage:400,kw:200,pf:.75,target:.95}});
const names={loadflow:'Radial load flow',fault:'Three-phase short circuit',generator:'Generator assessment',transformer:'Transformer assessment',pf:'Power factor correction'};
function num(o,k,min=0,max=Infinity,strict=false){const v=o[k];if(!Number.isFinite(v)||v<min||v>max||(strict&&v===min))throw Error(k+': enter a number '+(strict?'greater than ':'from ')+min+(max<Infinity?' to '+max:'')+'.');return v;}
function validate(k,s){if(!s||typeof s!=='object')throw Error('Missing study inputs.');
 if(k==='loadflow'){num(s,'voltage',0,Infinity,true);num(s,'minPU',0,2,true);num(s,'maxPU',s.minPU,2);if(!Array.isArray(s.buses)||!s.buses.length||s.buses.length>12)throw Error('Use 1–12 load buses.');s.buses.forEach((b,i)=>{if(!b||typeof b.name!=='string'||b.name.length>60)throw Error('Bus name must be text, up to 60 characters.');num(b,'parent',0,i);if(!Number.isInteger(b.parent))throw Error('Parent bus must be an integer.');for(const f of ['p','r','x'])num(b,f);num(b,'q',-1e8);num(b,'amps',0,Infinity,true);});}
 else if(k==='fault'){for(const f of ['voltage','sourceMVA','kva','z','factor'])num(s,f,0,Infinity,true);for(const f of ['sourceXR','txXR','r','x'])num(s,f);}
 else if(k==='generator'){for(const f of ['voltage','kva','xd'])num(s,f,0,Infinity,true);num(s,'ratedPF',0,1,true);num(s,'loadPF',0,1,true);num(s,'derating',0,100,true);num(s,'minLoad',0,100);num(s,'loadKW');num(s,'units',1,100);if(!Number.isInteger(s.units))throw Error('Generator count must be an integer.');}
 else if(k==='transformer'){for(const f of ['kva','hv','lv','z'])num(s,f,0,Infinity,true);for(const f of ['core','copper','loadKW'])num(s,f);num(s,'pf',0,1,true);if(s.copper/s.kva*100>s.z)throw Error('Rated load loss implies resistance greater than total impedance. Check kW and impedance %.');}
 else if(k==='pf'){num(s,'voltage',0,Infinity,true);num(s,'kw');num(s,'pf',0,1,true);num(s,'target',s.pf,1);}
 else throw Error('Unknown study.');
}
const add=(a,b)=>[a[0]+b[0],a[1]+b[1]],sub=(a,b)=>[a[0]-b[0],a[1]-b[1]],mul=(a,b)=>[a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]],abs=a=>Math.hypot(...a),conj=a=>[a[0],-a[1]],div=(a,b)=>{const d=b[0]**2+b[1]**2;return [(a[0]*b[0]+a[1]*b[1])/d,(a[1]*b[0]-a[0]*b[1])/d]};
function flow(s){validate('loadflow',s);const v0=s.voltage/Math.sqrt(3),n=s.buses.length;let volts=Array.from({length:n+1},()=>[v0,0]),currents,delta=Infinity,iteration=0;
 const backward=()=>{const ii=[[0,0],...s.buses.map((b,i)=>conj(div([b.p*1000/3,b.q*1000/3],volts[i+1])))];for(let j=n;j>0;j--)ii[s.buses[j-1].parent]=add(ii[s.buses[j-1].parent],ii[j]);return ii;};
 for(iteration=1;iteration<=200;iteration++){currents=backward();const next=[[v0,0]];for(let j=1;j<=n;j++){const b=s.buses[j-1];next[j]=sub(next[b.parent],mul([b.r,b.x],currents[j]));if(!Number.isFinite(abs(next[j]))||abs(next[j])<v0*.1)throw Error('Load flow did not converge to a usable voltage. Reduce load or check branch impedances.');}delta=Math.max(...next.map((v,i)=>abs(sub(v,volts[i]))));volts=next;if(delta<1e-7)break;}
 if(iteration>200)throw Error('Load flow did not converge after 200 sweeps. Results are unavailable.');currents=backward();
 const rows=s.buses.map((b,i)=>{const v=abs(volts[i+1])*Math.sqrt(3),a=abs(currents[i+1]);return {name:b.name,parent:b.parent,v,pu:v/s.voltage,angle:Math.atan2(volts[i+1][1],volts[i+1][0])*180/Math.PI,a,loading:a/b.amps*100,loss:3*a*a*b.r/1000,qloss:3*a*a*b.x/1000};});
 const source=mul(volts[0],conj(currents[0])).map(v=>v*3/1000),loss=rows.reduce((a,b)=>a+b.loss,0),p=s.buses.reduce((a,b)=>a+b.p,0),q=s.buses.reduce((a,b)=>a+b.q,0),qloss=rows.reduce((a,b)=>a+b.qloss,0);
 return {rows,iteration,loss,sourceP:source[0],sourceQ:source[1],sourceA:abs(currents[0]),minPU:Math.min(...rows.map(b=>b.pu)),balance:Math.hypot(source[0]-p-loss,source[1]-q-qloss),warnings:rows.flatMap(b=>[...(b.pu<s.minPU||b.pu>s.maxPU?[b.name+': voltage outside entered limits.']:[]),...(b.loading>100?[b.name+': branch exceeds entered ampacity.']:[])])};}
const rx=(z,xr)=>{const r=z/Math.sqrt(1+xr*xr);return [r,r*xr]};
function fault(s){validate('fault',s);const zs=rx(s.voltage*s.voltage/(s.sourceMVA*1e6),s.sourceXR),zt=rx(s.z/100*s.voltage*s.voltage/(s.kva*1000),s.txXR),total=add(add(zs,zt),[s.r,s.x]),ka=s.factor*s.voltage/(Math.sqrt(3)*abs(total))/1000;return {sourceZ:abs(zs),txZ:abs(zt),r:total[0],x:total[1],z:abs(total),ka,mva:Math.sqrt(3)*s.voltage*ka/1000,terminalKA:s.factor*s.voltage/(Math.sqrt(3)*abs(add(zs,zt)))/1000,warnings:[]};}
function generator(s){validate('generator',s);const ratedKW=s.kva*s.ratedPF,unitKW=ratedKW*s.derating/100,unitKVA=s.kva*s.derating/100,loadKVA=s.loadKW/s.loadPF,required=Math.max(Math.ceil(s.loadKW/unitKW),Math.ceil(loadKVA/unitKVA)),unitLoad=s.loadKW/s.units;return {ratedA:s.kva*1000/(Math.sqrt(3)*s.voltage),loadA:loadKVA*1000/(Math.sqrt(3)*s.voltage),loadKVA,kvar:s.loadKW*Math.tan(Math.acos(s.loadPF)),unitKW,unitKVA,kwLoading:unitLoad/unitKW*100,kvaLoading:loadKVA/s.units/unitKVA*100,minKW: ratedKW*s.minLoad/100,required,withSpare:required+1,faultKA:s.kva*1000/(Math.sqrt(3)*s.voltage)/(s.xd/100)/1000,warnings:[...(required>s.units?['Online fleet cannot carry the entered steady-state load.']:[]),...(required>s.units-1?['Entered online fleet does not meet one-unit-out steady-state capacity.']:[]),...(unitLoad<ratedKW*s.minLoad/100?['Equal sharing puts each online unit below the entered minimum load.']:[])]};}
function transformer(s){validate('transformer',s);const kva=s.loadKW/s.pf,loading=kva/s.kva,rpct=s.copper/s.kva*100,xpct=Math.sqrt(Math.max(0,s.z*s.z-rpct*rpct)),loss=s.core+s.copper*loading*loading;return {primaryA:s.kva*1000/(Math.sqrt(3)*s.hv),secondaryA:s.kva*1000/(Math.sqrt(3)*s.lv),loadA:kva*1000/(Math.sqrt(3)*s.lv),loadKVA:kva,loading:loading*100,rpct,xpct,drop:loading*(rpct*s.pf+xpct*Math.sqrt(1-s.pf*s.pf)),loss,efficiency:s.loadKW+loss?100*s.loadKW/(s.loadKW+loss):0,faultKA:s.kva*1000/(Math.sqrt(3)*s.lv)/(s.z/100)/1000,warnings:loading>1?['Load exceeds transformer nameplate kVA.']:[]};}
function pf(s){validate('pf',s);const kvar=s.kw*(Math.tan(Math.acos(s.pf))-Math.tan(Math.acos(s.target))),before=s.kw/s.pf,after=s.kw/s.target;return {kvar,before,after,freed:before-after,currentBefore:before*1000/(Math.sqrt(3)*s.voltage),currentAfter:after*1000/(Math.sqrt(3)*s.voltage),warnings:[]};}
function clean(state){const d=defaults();if(state===undefined)return d;if(!state||typeof state!=='object')throw Error('Invalid saved study settings.');for(const k of Object.keys(d)){if(state[k]!==undefined){d[k]=JSON.parse(JSON.stringify(state[k]));validate(k,d[k]);}}return d;}
function checked(k,s){validate(k,s);const r=({loadflow:flow,fault,generator,transformer,pf}[k])(s);const inspect=o=>{for(const v of Object.values(o)){if(typeof v==='number'&&!Number.isFinite(v))throw Error('Calculation exceeds numeric range. Check units and input magnitudes.');if(v&&typeof v==='object')inspect(v);}};inspect(r);return r;}
const api={defaults,names,validate,clean,run:checked};root.StudyModel=api;if(typeof module==='object')module.exports=api;
})(globalThis);
